Repository jaegertracing/jaeger-client-java, pull requests merged in 2018-07, with the labels that each got.

#474 Prepare release 0.30.0
  CHANGELOG.md
  build.gradle
Labels: review

#475 Back to development 0.30.1-SNAPSHOT
  CHANGELOG.md
  build.gradle
Labels: review

#476 Fix links to PRs on changelog for v0.30.0
  CHANGELOG.md
Labels: review

#478 Fix version retrieval from jaeger.properties
  .gitignore
  jaeger-core/build.gradle
  jaeger-core/src/main/resources/io/jaegertracing/internal/jaeger.properties
Labels: review

#457 Make GuaranteedThroughputSampler public
  jaeger-core/src/main/java/io/jaegertracing/internal/samplers/GuaranteedThroughputSampler.java
Labels: review

#480 Fix wrong package declaration
  jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java
  jaeger-core/src/main/java/io/jaegertracing/internal/clock/Clock.java
  jaeger-core/src/main/java/io/jaegertracing/internal/clock/SystemClock.java
  jaeger-core/src/main/java/io/jaegertracing/internal/utils/RateLimiter.java
  jaeger-core/src/test/java/io/jaegertracing/internal/JaegerSpanTest.java
  jaeger-core/src/test/java/io/jaegertracing/internal/utils/RateLimiterTest.java
Labels: review

#479 Add jaeger-client module
  README.md
  jaeger-client/README.md
  jaeger-client/build.gradle
  jaeger-client/src/main/java/io/jaegertracing/client/Version.java
  jaeger-client/src/test/java/io/jaegertracing/client/VersionTest.java
  jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java
  settings.gradle
Labels: review

#481 Add "serialVersionUID" for exceptions to avoid InvalidClassException
  jaeger-core/src/main/java/io/jaegertracing/internal/exceptions/BaggageRestrictionManagerException.java
  jaeger-core/src/main/java/io/jaegertracing/internal/exceptions/EmptyIpException.java
  jaeger-core/src/main/java/io/jaegertracing/internal/exceptions/EmptyTracerStateStringException.java
  jaeger-core/src/main/java/io/jaegertracing/internal/exceptions/MalformedTracerStateStringException.java
  jaeger-core/src/main/java/io/jaegertracing/internal/exceptions/NotFourOctetsException.java
  jaeger-core/src/main/java/io/jaegertracing/internal/exceptions/SamplingStrategyErrorException.java
  jaeger-core/src/main/java/io/jaegertracing/internal/exceptions/SenderException.java
  jaeger-core/src/main/java/io/jaegertracing/internal/exceptions/UnsupportedFormatException.java
Labels: review

#483 Specify custom sender for tests in the module jaeger-client
  jaeger-client/build.gradle
  jaeger-client/src/test/java/io/jaegertracing/client/VersionTest.java
  jaeger-client/src/test/resources/META-INF/services/io.jaegertracing.spi.SenderFactory
  jaeger-core/src/main/java/io/jaegertracing/internal/senders/NoopSenderFactory.java
  jaeger-core/src/main/java/io/jaegertracing/internal/senders/SenderResolver.java
  jaeger-core/src/test/java/io/jaegertracing/internal/senders/SenderResolverTest.java
Labels: enhancement, review

#482 Prepare release 0.30.1
  CHANGELOG.md
  build.gradle
Labels: review

#485 Back to development 0.30.2-SNAPSHOT
  CHANGELOG.md
  build.gradle
Labels: review

#487 Fix issue where warning message is generated each time a null referen…
  jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java
  jaeger-core/src/test/java/io/jaegertracing/internal/JaegerSpanTest.java
  jaeger-core/src/test/java/io/jaegertracing/internal/JaegerTracerTest.java
Labels: review

#486 Fix jaeger-client dependency jaeger-thrift no-shadow artifact
  jaeger-client/build.gradle
  jaeger-client/src/test/java/io/jaegertracing/client/VersionTest.java
  jaeger-crossdock/build.gradle
  jaeger-zipkin/build.gradle
Labels: review

#489 Fix Zipkin readme
  jaeger-zipkin/README.md
Labels: bug, documentation, review

#491 Prepare release 0.30.2
  CHANGELOG.md
  build.gradle
Labels: review

#492 Back to development 0.30.3-SNAPSHOT
  CHANGELOG.md
  build.gradle
Labels: review

#504 Prepare release 0.30.3
  CHANGELOG.md
  build.gradle
Labels: review

#505 Back to development 0.30.4-SNAPSHOT
  CHANGELOG.md
  build.gradle
Labels: review
